name: Lint HTML & CSS

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - name: Grant execution permissions
        run: chmod +x ./node_modules/.bin/htmlhint
      - run: npm run lint:html

